steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
  with:
    python-version: '3.10' 

ports:
- port: 8000
  onOpen: open-preview

tasks:
- before: pip3 install -r requirements.txt
  command: make live-html
