[build]
  publish = "_build/html"
  command = "make netlify"
  environment = { BASE_URL = "https://esphome.io" }

[build.processing]
  # only size-minimize everything in production
  skip_processing = true
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true

[context.beta]
  environment = { BASE_URL = "https://beta.esphome.io" }

[context.next]
  environment = { BASE_URL = "https://next.esphome.io" }

[context.production]
  environment = { BASE_URL = "https://esphome.io", PRODUCTION = "YES" }
[context.production.processing]
  skip_processing = false

# A basic redirect rule
[[redirects]]
  from = "/esphomeyaml/*"
  to = "/:splat"
